In [1]:
import numpy as np

In [2]:
# Create a 2D numpy array
a = np.array([[2,4,6,8,10,12,14],[1,3,5,7,9,11,13]])

In [3]:
# Create a 1D numpy array with an explicit datatype
b = np.array([2,4,6], dtype='int16')

In [4]:
# Get dimension of the array
print(a.ndim)
print(b.ndim)

2
1


In [5]:
# Shape of teh array
print(a.shape)
print(b.shape)

(2, 7)
(3,)


In [6]:
# Datatype of the array
print(a.dtype)
print(b.dtype)

int32
int16


In [7]:
# Byte size of an entry/item in the array
print(a.itemsize)
print(b.itemsize)

4
2


In [8]:
# Byte size of the complete array
print(a.nbytes)
print(b.nbytes)

56
6


## Accessing and changing specific elements

In [9]:
# Get a specific element. Indexes start from zero
a[1,4]

9

In [10]:
# Get a row
a[0, :]

array([ 2,  4,  6,  8, 10, 12, 14])

In [11]:
# Get a column
a[:, 2]

array([6, 5])

In [12]:
# Get a range of indexes. [start index : end index : step size]
a[:, 2:6:2]

array([[ 6, 10],
       [ 5,  9]])

In [13]:
# Change an element
a[1,4] = 100
a

array([[  2,   4,   6,   8,  10,  12,  14],
       [  1,   3,   5,   7, 100,  11,  13]])

In [14]:
# Change a range of selection
a[:, 2] = [71, 72]
a

array([[  2,   4,  71,   8,  10,  12,  14],
       [  1,   3,  72,   7, 100,  11,  13]])

In [15]:
## Array initialization techniques

In [16]:
# Matrix with all zeroes
np.zeros([2,6,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
# Matrix with all ones
np.ones([2,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
# Matrix with specified value
np.full([2,6], 72)

array([[72, 72, 72, 72, 72, 72],
       [72, 72, 72, 72, 72, 72]])

In [19]:
# Matrix with random numbers
np.random.rand(2,4)

array([[0.40810775, 0.86374981, 0.94715222, 0.07670378],
       [0.90952063, 0.10165405, 0.38437944, 0.18258223]])

In [20]:
# Matrix with random numbers with the shape of another array
np.random.random_sample(a.shape)

array([[0.58904117, 0.3857249 , 0.36224175, 0.21710351, 0.71181402,
        0.08978284, 0.70614526],
       [0.1118906 , 0.91549368, 0.92565052, 0.2674102 , 0.64643549,
        0.73749923, 0.03983826]])

In [21]:
# Matrix with random "integer" numbers below 20
np.random.randint(20, size=(2,4))

array([[11,  2, 10, 13],
       [ 4,  5, 15,  4]])

In [22]:
# Matrix with random "integer" numbers above -10 and below 20
np.random.randint(-10, 20, size=(2,4))

array([[ 4,  7, -9, 11],
       [ 8, 16,  4,  4]])

In [23]:
# Repeat an array on the row dimension or 1st dimension of the N dimensions of a shape array (axis = n)
# In a 2D array axis 0 means row and 1 means column
np.repeat(a, 3, axis=0)

array([[  2,   4,  71,   8,  10,  12,  14],
       [  2,   4,  71,   8,  10,  12,  14],
       [  2,   4,  71,   8,  10,  12,  14],
       [  1,   3,  72,   7, 100,  11,  13],
       [  1,   3,  72,   7, 100,  11,  13],
       [  1,   3,  72,   7, 100,  11,  13]])

In [24]:
# An exercise to build a long array with bulk operation commands
x = np.full([5,6], 5)
x[1:4, 1:5] = np.zeros([3,4])
x[2, 2:4] = 7
print(x)
del x

[[5 5 5 5 5 5]
 [5 0 0 0 0 5]
 [5 0 7 7 0 5]
 [5 0 0 0 0 5]
 [5 5 5 5 5 5]]


In [25]:
# Copying or cloning an array
x = a.copy()
print(a[0,0])
x[0,0] = 15
print(x[0,0])
print(a[0,0])

2
15
2


In [26]:
## Statistical functions examples

In [27]:
x = np.array([[1,5,3],[4,2,6]])
print(x)
print(np.min(x, axis=0))
print(np.max(x))
print(np.sum(x, axis=0))
print(np.mean(x, axis=0))
del x

[[1 5 3]
 [4 2 6]]
[1 2 3]
6
[5 7 9]
[2.5 3.5 4.5]


In [28]:
## Array Re-organzation

In [29]:
# Reshape an array into a different shape
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.reshape(4,2))
print(x.reshape(2,2,2))
print(x.reshape(4,1,2))
del x

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


In [30]:
# Vertically stacking vectors
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

np.vstack([x,y,x,y,y])
del x
del y

In [31]:
# Horizontal stack
x = np.zeros([2,4])
y = np.ones([2,2])

np.hstack([x,y])
del x
del y

In [32]:
## Load data from file

In [33]:
x = np.genfromtxt('../dataset/simple_numbers.csv', delimiter=',')
x = x.astype('int32')
print(x)
del x

[[68 50 67 90 40 13 91 16 10 13]
 [18 95 82 94 26 22 50 63 89 96]
 [42 70 59 30 93 58 55 47 55 91]
 [17 11 46 80 82 89 90 11 82 22]]


In [34]:
## Boolean masking and advanced indexing

In [35]:
x = np.random.randint(1, 100, size=(5, 10))
print(x)
print(x > 50)
print(x[x > 50])

# If any row or value on the 0th axis fulfills the condition
print(np.any(x > 50, axis=0))
print((x > 25) & (x < 50))
print(~((x > 25) & (x < 50)))

[[15 73 89  3 20 76 64  1 27 13]
 [13 11 70 73 83 44 95 43 33 28]
 [56 83 79 88 19 83 66 99 20 13]
 [ 3  6 83 73 53  1 85  9 78  9]
 [20 37 80  6 83 42  2 78 70 55]]
[[False  True  True False False  True  True False False False]
 [False False  True  True  True False  True False False False]
 [ True  True  True  True False  True  True  True False False]
 [False False  True  True  True False  True False  True False]
 [False False  True False  True False False  True  True  True]]
[73 89 76 64 70 73 83 95 56 83 79 88 83 66 99 83 73 53 85 78 80 83 78 70
 55]
[ True  True  True  True  True  True  True  True  True  True]
[[False False False False False False False False  True False]
 [False False False False False  True False  True  True  True]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True False False False  True False False False False]]
[[ True  True  True  True  True  True  True  True False  True]

In [36]:
# You can index with a list
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[[1,2,8]])
del x

[2 3 9]
